config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks,only:[:create,:destroy]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get  'friends', to: 'users#friends'
  get 'search', to: 'users#search'
  resources :friendships,only:[:create, :destroy]
  resources :users,only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to:user
  belongs_to:friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  validates :name, :ticker, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  def full_name
   return "#{first_name} #{last_name}" if first_name || last_name
   "Anonymus"
  end
  def self.search(param)
    param.strip!
    match_results = (first_name_matches(param)+last_name_matches(param)+email_matches(param)).uniq
    return nil  if match_results.empty?

    match_results
  end
  def self.first_name_matches(param)
    matches('first_name',param)
  end
  def self.last_name_matches(param)
    matches('last_name',param)
  end
  def self.email_matches(param)
    matches('email',param)
  end
  def self.matches(field_name,param)
    where("#{field_name} like ?","%#{param}%")
  end
  def not_friends_with?(id_of_friend)
   !self.friends.where(id: id_of_friend).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
 def create
   friend = User.find(params[:friend])
   current_user.friendships.build(friend_id: friend.id)
   if current_user.save
     flash[:notice] = "following user"
   else
     flash[:alert] = "there is something wrong"
   end
   redirect_to friends_path
 end
 def destroy

   friendship = current_user.friendships.where(friend_id: params[:id]).first
   friendship.destroy
   flash[:notice] = "succefully removed"
   redirect_to friends_path
 end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock=Stock.check_db(params[:ticker])
  end
#  def destroy
#user_stock = User.Stock.where(user_id: current_user.id, stock_id: stock.id).first
#user_stock.destroy
#flash[:notice] = "#{stock.ticker }was succefully removed from your poprtfolio"
#redirect_to my_portfolio_path
#  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def my_portfolio
   @user = current_user
  @tracked_stocks = current_user.stocks
 end
 def friends
   @f = current_user.friends
   @users=User.all
 end

 def show
  @user = User.find(params[:id])
    @tracked_stocks = current_user.stocks
 end

 def search
 #render json: params[:friend]
 if params[:friend].present?
      @friends = User.search(params[:friend])
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        #respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          #format.js { render partial: 'users/friend_result' }
      #  end
      end
  else
      #respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search"
        #format.js { render partial: 'users/friend_result' }
      #end
  end
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/layouts/_messages.html.erb
<p class="notice" ,style="color:green"><%= notice %></p>
<p class="alert", style="color:red" > <%= alert %></p>

app/views/layouts/_navigation.html.erb
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="container-fluid">

    <a class="navbar-brand" href="#"><%= link_to 'Finance Tracker',root_path %></a>
    <% if current_user %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
<%= link_to 'My Portfolio', my_portfolio_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><%= link_to 'Friends',friends_path %></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
            <li class="nav-item user-name">
          <u>  <%= current_user.full_name %></u></li>

        <li class="nav-item ">
          <%= link_to 'logout',destroy_user_session_path,class:"logout_btn" ,method: :delete %></li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      </div>
  <% end %>
  </div>

</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinancceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <%= render 'layouts/navigation' %>
<div class="container">
   <%= render 'layouts/messages' %>
    <%= yield %>
</div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-8">
<table class="table">
  <thead>
    <tr >
      <th scope="col">Ticker</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tracked_stocks.each do |stock| %>
    <tr>
      <th scope="row"><%= stock.ticker %></th>
      <td ><%= stock.name%></td>
      <td><%= stock.last_price%></td>
      <td><% if current_user.id  == @user.id %> <%= link_to 'remove',user_stock_path(stock), method: :delete, data: {confirm:"are you sure want to delete"}  %>
       <% else %>
       Follow
       <% end %>
      </td>
    </tr>
     <% end %>
  </tbody>
</table>
<div>
  </div>

app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @friends %>
  <div class="card card-header results-block">
    <%= @friends.each do |friend| %>
    <strong>Email: </strong> <%= friend.full_name %>
    <strong>Name: </strong> <%= friend.email %>
    <strong>Profile: </strong> <%= link_to 'View Profile','#',class:"btn btn-sm btn-success" %>
    <%= link_to 'Follow friend?', '#',
                            class: "btn btn-sm btn-success", method: :post %>
  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'users/friend_result.html' %>'

app/views/users/friends.html.erb
<h2> My Friends  </h2>


<% if !@f.empty?%>
 <% @f.each do |f1| %>
 <%= f1.first_name %> <%= f1.email %> <%= link_to 'View profile',user_path(f1) %> <%= link_to "remove",friendship_path(f1), method: :delete, data: {confirm: 'are you confirm'}  %><br>
 <% end%>
<% else%>
  <%= "you are not following any of your friends" %>
<% end %>



<div id="friend-results">

</div>
<div class='search-area'>
  <h3>Search Friends</h3>
  <%= form_tag search_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Name or email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>

        <% end %>
      </div>
    </div>
<% end %>
</div>

<table>

    <% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td> <%= user.email%></td>
    <td><% if current_user.not_friends_with?(user.id) %><%= link_to 'add to friend',friendships_path(friend: user),method: :post %>
        <% else %>
        Already friends
        <% end %>
    </td>
</tr>
    <% end %>

</table>

app/views/users/my_portfolio.html.erb
<h2>My_Portfolio </h2>

<% if !@tracked_stocks.empty? %>
<%= render 'stocks/list' %>
<% end %>

app/views/users/search.html.erb
<h3>search Friends</h3>
hgfcyj

app/views/users/show.html.erb
 <%= @user.first_name %> <%= @user.email %>
 <br>
 <% if current_user.not_friends_with?(@user.id) %><%= link_to 'add to friend',friendships_path(friend: @user),method: :post %>
     <% else %>
     Already friends
     <% end %>

     <% if !@tracked_stocks.empty? %>
        <%= render 'stocks/list' %>
     <% else %>
     <p> This your not tracking any stocks </p>
     <% end %>

app/views/welcome/index.html.erb
<center><h2> Welcome to Home </h2> </center>

<%= link_to 'sign out',destroy_user_session_path, method: :delete %>